org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod
mod_id=fuelblast
mod_name=Create: Fuel Blast
mod_version=0.1.0
mod_group=com.danzy.fuelblast
mod_authors=Danzy-189
mod_license=MIT

# Platform
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

# Dependencies
create_version=0.5.1.f-33
registrate_version=MC1.20.1-1.3.3
flywheel_version=0.6.10-7
